### PR TITLE
Remove HAVE_LIBJPEG, HAVE_LIBPNG and HAVE_LIBTIFF.

### PR DESCRIPTION
**Pull request by Wolf3s**

### CODE REVIEW

**Comment by fjtrujy** [comment]
I'm not 100% if we sure remove it... so far `gskit` was thought to be built without any other further dependency besides `ps2sdk`, however, now given the current toolchain workflow installation always happens after installing libpng and so on, this is why CI still passes it.

I think that probably the best is to generate additional `gskit` libraries which provide functionality for jpeg, png and libtiff.
What do you think @rickgaiser ?

**Comment by Wolf3s** [comment]
> I'm not 100% if we sure remove it... so far `gskit` was thought to be built without any other further dependency besides `ps2sdk`, however, now given the current toolchain workflow installation always happens after installing libpng and so on, this is why CI still passes it.
> 
> I think that probably the best is to generate additional `gskit` libraries which provide functionality for jpeg, png and libtiff. What do you think @rickgaiser ?

You mean remove all the libraries and add a implementation from scratch for jpg, ttf and tiff? If Yes i would like to see that.

**Comment by fjtrujy** [comment]
> > I'm not 100% if we sure remove it... so far `gskit` was thought to be built without any other further dependency besides `ps2sdk`, however, now given the current toolchain workflow installation always happens after installing libpng and so on, this is why CI still passes it.
> > I think that probably the best is to generate additional `gskit` libraries which provide functionality for jpeg, png and libtiff. What do you think @rickgaiser ?
> 
> You mean remove all the libraries and add a implementation from scratch for jpg, ttf and tiff? If Yes i would like to see that.

No, I mean to create separate gsKit libraries adding that functionality, like gskit_jpg, gskit_png…

**Comment by uyjulian** [comment]
I think it would be better to have functions in separate compilation units to enable and register the function for the specific image format. So if you don't use those functions you don't need to link the library

**Comment by Wolf3s** [comment]
> > > I'm not 100% if we sure remove it... so far `gskit` was thought to be built without any other further dependency besides `ps2sdk`, however, now given the current toolchain workflow installation always happens after installing libpng and so on, this is why CI still passes it.
> > > I think that probably the best is to generate additional `gskit` libraries which provide functionality for jpeg, png and libtiff. What do you think @rickgaiser ?
> > 
> > 
> > You mean remove all the libraries and add a implementation from scratch for jpg, ttf and tiff? If Yes i would like to see that.
> 
> No, I mean to create separate gsKit libraries adding that functionality, like gskit_jpg, gskit_png…

I aprove that, since gsKit wasn't made for that purpose.

**Comment by Wolf3s** [comment]
Moving on a another request

**Pull request closed without merging**
