### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by rickgaiser**
The 12 year old bug causes a memory leak for persistent queues when transferring textures. Most applications don't use persistent queues, and if they do they don't use it for transferring textures. Unfortunately hires mode only uses persistent queues and it made some hires applications crash after a while.

There was also a strange issue with semaphore polling. The semaphores used can be max 1, but somehow I need to poll the semaphore more than once to make it go 0.

### CODE REVIEW

**Comment by sp193** [comment]
For the EE kernel, SignalSema can cause the semaphore's count to exceed its maximum count (there is no runtime check).

**Comment by rickgaiser** [comment]
Thank you for the info. If that's how SignalSema works then I think this is a good solution. If you're ok with the solution too then go ahead and merge.

**Comment by lancegilbert** [comment]
Hi Guys! This is Chris Gilbert (the original author) and thank you so much for continuing to fix this ancient code, I hope it's still useful to someone :)

If I recall correctly, the Sema stuff was added after I stopped maintaining the project but if you have any other questions please don't hesitate to ask and I will do my best to remember... :)

PS: Please add yourselves to the AUTHORS file!

**Comment by sp193** [comment]
Thank you @lancegilbert for your contribution of gsKit!

SignalSema works this way, since the kernel was first implemented as such and so SONY just kept all version that way for backward and forward compatibility.
This lack of an explicit check on the semaphore's maximum count before incrementation is only one of the things that don't work in the EE kernel anyway. :P

**Comment by rickgaiser** [comment]
@lancegilbert sorry for the late reply. gsKit is still being actively used. Just want to thank you for stopping by your old project and creating it in the first place.

**Pull request merged**
