### PR TITLE
New samll commit

### PR DESCRIPTION
**Pull request by AKuHAK**
Now install target can be called without calling all target first.
Added DESTDIR.
Small fixes in text files
Warnings fixed.
These [issue ](https://github.com/ps2dev/gsKit/issues/1)can be closed

### CODE REVIEW

**Comment by sp193** [comment]
Everything else looks good, but what's with the addition of "Wno-unused"? Can't those warnings be fixed the right way around? After all, we desire efficiency.
I added that option to some projects like the LWIP ports, but only because I didn't want to fix the warnings in external projects.

**Comment by sp193** [comment]
BTW, this pull request is fine, no need to make any changes. I would just like to know why it's necessary, in case there is actually a good reason why the unused variables cannot be removed. It'll save everyone time.

**Comment by AKuHAK** [comment]
Oh there is already -Wno-unused in gstoolkit and dma sub projects. Only gsKit itself lacks this option. I just assumed that it is safe to add it cause all unused variables in most common cases are used in printf output (in fact I dont know why gcc thinks that it is mean "unused")

**Comment by sp193** [comment]
Okay, thanks. I'll take a look at it, when time permits.

**Pull request merged**
