### PR TITLE
Various fixes for new toolchain

### PR DESCRIPTION
**Pull request by uyjulian**

### CODE REVIEW

**Comment by rickgaiser** [comment]
Commit 912b019 looks good to me.

Commit e8d8e2c :
If the toolchain provides the proper crt0.o file, we don't need to manually override these settings in all our ps2 makefiles. crt0.o is generated from crt0.S and should be in newlib, not in ps2sdk.

It's actually already in newlib, but it's never been updated while the version in ps2sdk is. For the newlib port I've moved crt0.S from ps2sdk to newlib. Commit here:
https://gitlab.com/ps2max/toolchain/newlib/-/commit/39fd2f043b9b349db5aaf438fc277474577e7242
Perhaps you can use this approach in your new toolchain as well?

**Comment by uyjulian** [comment]
For the time being, the new toolchain is based on upstream. I plan to rebase to newlib port later.

**Comment by uyjulian** [comment]
Rebased and dropped the Makefile changes.

**Comment by rickgaiser** [comment]
Perfect, thanks. Merging.

**Comment by AKuHAK** [comment]
Probably issue #24 can be closed as well?

**Pull request merged**
